_format_version: "1.1"
routes:
  - name: grafana-root-path
    service: grafana-service
    https_redirect_status_code: 426
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
      - HEAD
    paths:
      - /grafana
    preserve_host: true
    protocols:
      - http
      - https
    regex_priority: 100
    request_buffering: true
    response_buffering: true
    strip_path: false
