_format_version: "1.1"
routes:
  - name: user-profile
    service: fleet-management-service
    https_redirect_status_code: 426
    methods:
      - GET
      - PUT
    paths:
      - /api/v1/users/profile
    preserve_host: false
    protocols:
      - http
      - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false

  - name: user-preferences
    service: fleet-management-service
    https_redirect_status_code: 426
    methods:
      - GET
      - POST
      - PUT
    paths:
      - /api/v1/users/preferences
    preserve_host: false
    protocols:
      - http
      - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false

  - name: user-notifications
    service: fleet-management-service
    https_redirect_status_code: 426
    methods:
      - GET
      - POST
    paths:
      - /api/v1/users/notifications
    preserve_host: false
    protocols:
      - http
      - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false

  - name: user-activity
    service: fleet-management-service
    https_redirect_status_code: 426
    methods:
      - GET
    paths:
      - /api/v1/users/activity
    preserve_host: false
    protocols:
      - http
      - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: false
